language: go
deploy:
  provider: gae
  keyfile: client-secret.json
  project: wrabit-webapp
  default: true
  skip_cleanup: true
before_install:
- openssl aes-256-cbc -K $encrypted_e626bbe42ecb_key -iv $encrypted_e626bbe42ecb_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv .prod.env .env