language: go
go:
- 1.13.x
before_install:
- openssl aes-256-cbc -K $encrypted_e626bbe42ecb_key -iv $encrypted_e626bbe42ecb_iv
  -in secrets.tar.enc -out secrets.tar -d
- rm Makefile
- tar xvf secrets.tar
deploy:
- provider: gae
  config: stage.yaml
  keyfile: gcp-deploy.json
  project: wrabit-webapp
  default: true
  skip_cleanup: true
- provider: gae
  config: prod.yaml
  keyfile: gcp-deploy.json
  project: wrabit-webapp
  default: true
  skip_cleanup: true
