language: go
deploy:
  provider: gae
  keyfile: client-secret.json
  project: wrabit-webapp
  default: true
before_install:
- openssl aes-256-cbc -K $encrypted_e626bbe42ecb_key -iv $encrypted_e626bbe42ecb_iv
  -in client-secret.json.enc -out client-secret.json -d
env:
  global:
  - CLOUDSQL_CONNECTION_NAME=wrabit-webapp:us-central1:wrabit-postgres
  - CLOUDSQL_DATABASE_NAME=wrabit
  - secure: lAqjAkl3PzcVq1HQiRWP6JLwVtnPXH2I0Gwb3f2xWu6nocPpM4yKXuQUyOJ9WT1DhroLASUmcWB/+Aq32/yVtJZ4p1MoFt63k8QzpSVBV+tW98iSqz207MtgCe+49vwVMxWhEYvLLFlh0KySppb2dsGvlVtLruT0zvPd11qnrTHxykn885DW9CeSS3DVquYQv68rqezaYCJUwrIZc7MqbSlOvxJdVcL9U5yp6buvSib2WwUBnS7uHIyoyATPKWE2tQr81+TYJRxLoTYJOqnEqS/UJ3BpAwUqqkVTcsawFQUdblv4CaVU3TT9C5osAlgPXaJXJa5B4sAn1vm0PmiMHmiD29vZtYkZeQHPAkZQow3UVmd9mhx5Ye+9ffCMT5/Mb5XUq38pjdw48i7LkP70cPoUNAEYsnBNxUjNrmlFHIlV5z+hCU/TOQ8pt7q5H2KS8QWifAiUlO2Irlx5TiqjrwZbPe4dGgkmYrA8nDX3eByyf8C3ZCK+Kqw3aoa06937WTLntWog1pqH/c80v6wHSFnYhYogRonUY9uHKrxXt28AtK6//avj1KpJ/UnmLIGkaiMB1n78D4vj9ou9ew2Hd33evLRzxSuSskURiz7vxqxOcDswXtz+oXExhcK7tja40AnTIkAgcPP9rrgp5B0RV3k+D/kOO3HrCbQ3DmknEbA=
  - secure: hrsFQEWp8qmMCkWZaqDqO952qKOg+3G7uvYS/N5T5UhzRBCJByBiXIgUSllnTIVkMMf/DuDiqBhUeMapDWdcrSju/1Z9qlZMnnf1i97nIge8prtxKIUP3L4CEjWNU2d6cg+6ZS2ejztIUHax0+3cmi0p3WENCKcDvUesPElyTS0bf3rGiwBcbNYrq0D7whQfmH2r6RqFj3Zbga2Ph0l6I/yNW1G46yt76xiPjS7aG0WchUJlq/t9+anHKbR6Qi+Cxyw9QB0RcXdWclQG8FhPP2Iu0fSsueR6TwKc3BuUGC2s54CQidcSx9OynZcTa5pWaM/W/fB+K10u6Tjt7g2IaWIvubZXUqmR5sjxElFJfSc+DpR2gxPdqAcm+cUgIMLPGrRrsAKsKIVD4yMQ+JaKWoYnnUZ5NpVaqmLjBtLri6F2x02wDS3ZMYgrcUCQR2YenoiAxfrWCZlG6/iecqLir96LpZo//vs5PSlZWX/b8W7l1rRQF58duK2WAseQlxJ6GcKmj/CCPHAUWDXg1C2hElwyexTq5Mhe6Lea2DJGxqDtyAbJfy7EIn0daPYUFyMgMZNW5Pm0YSEN4XOFWhvJJEcvSlbb/ZAT5zuNwZAnzLMj0xNMCEX30z79d6807n8/6EJK4xWHoqw7RA3JLtBU49ZVByhNh7LUIP9u+Y0fO7E=
