// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package server

type NewEditor struct {
	UserID      string `json:"userId"`
	ShowToolbar bool   `json:"showToolbar"`
	ShowPrompt  bool   `json:"showPrompt"`
	ShowCounter bool   `json:"showCounter"`
}

type NewEntry struct {
	UserID    string `json:"userId"`
	WordCount int    `json:"wordCount"`
	Content   string `json:"content"`
}

type NewUser struct {
	FirebaseID string  `json:"firebaseID"`
	FirstName  string  `json:"firstName"`
	LastName   *string `json:"lastName"`
	Email      string  `json:"email"`
}

type User struct {
	ID         string  `json:"id"`
	FirebaseID string  `json:"firebaseID"`
	FirstName  string  `json:"firstName"`
	LastName   *string `json:"lastName"`
	Email      string  `json:"email"`
	WordGoal   int     `json:"wordGoal"`
}
